# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.FileField(upload_to='static/images/%Y/%m/%d/')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
